package cli

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"net/url"
	"os"
	"strings"
)

func handleInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(os.Stdout)

	output := fs.String("output", ".env", "Output env file path")
	force := fs.Bool("force", false, "Overwrite output file if it exists")
	siteURL := fs.String("site-url", "http://localhost:8090", "Public API URL")
	appDomain := fs.String("app-domain", "localhost", "Application base domain")
	databaseURL := fs.String("database-url", "", "PostgreSQL connection string")
	strictSecurity := fs.Bool("strict-security", false, "Enable strict startup security checks")
	debug := fs.Bool("debug", false, "Enable debug mode")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if strings.TrimSpace(*siteURL) == "" {
		return errors.New("site-url is required")
	}
	if strings.TrimSpace(*appDomain) == "" {
		return errors.New("app-domain is required")
	}
	if _, err := url.ParseRequestURI(*siteURL); err != nil {
		return fmt.Errorf("invalid --site-url: %w", err)
	}

	if _, err := os.Stat(*output); err == nil && !*force {
		return fmt.Errorf("file already exists: %s (use --force to overwrite)", *output)
	}

	jwtSecret, err := randomHex(64)
	if err != nil {
		return fmt.Errorf("generate JWT secret: %w", err)
	}

	allowedOrigins := deriveOrigins(*siteURL, *appDomain)
	envContent := renderEnv(initEnvData{
		SiteURL:         *siteURL,
		AppDomain:       *appDomain,
		AllowedOrigins:  strings.Join(allowedOrigins, ","),
		JWTSecret:       jwtSecret,
		DatabaseURL:     strings.TrimSpace(*databaseURL),
		StrictSecurity:  *strictSecurity,
		Debug:           *debug,
		RateLimitRPS:    "20",
		RateLimitBurst:  "20",
		BodyLimit:       "10M",
		DefaultSMTPPort: "587",
	})

	if err := os.WriteFile(*output, []byte(envContent), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", *output, err)
	}

	fmt.Printf("env file created: %s\n", *output)
	fmt.Println("next: fill DATABASE_URL if empty, then run: ozybase")
	return nil
}

type initEnvData struct {
	SiteURL         string
	AppDomain       string
	AllowedOrigins  string
	JWTSecret       string
	DatabaseURL     string
	StrictSecurity  bool
	Debug           bool
	RateLimitRPS    string
	RateLimitBurst  string
	BodyLimit       string
	DefaultSMTPPort string
}

func renderEnv(data initEnvData) string {
	dbURL := data.DatabaseURL
	if dbURL == "" {
		dbURL = "postgres://user:pass@db-host:5432/dbname?sslmode=require"
	}

	return fmt.Sprintf(`# Generated by: ozybase init
PORT="8090"
SITE_URL="%s"
APP_DOMAIN="%s"
ALLOWED_ORIGINS="%s"

JWT_SECRET="%s"
OZY_STRICT_SECURITY="%t"
DEBUG="%t"

DATABASE_URL="%s"
RATE_LIMIT_RPS="%s"
RATE_LIMIT_BURST="%s"
BODY_LIMIT="%s"

SMTP_HOST=""
SMTP_PORT="%s"
SMTP_USER=""
SMTP_PASSWORD=""
SMTP_FROM="noreply@%s"
`, data.SiteURL, data.AppDomain, data.AllowedOrigins, data.JWTSecret, data.StrictSecurity, data.Debug, dbURL, data.RateLimitRPS, data.RateLimitBurst, data.BodyLimit, data.DefaultSMTPPort, data.AppDomain)
}

func deriveOrigins(siteURL, appDomain string) []string {
	out := []string{strings.TrimRight(siteURL, "/")}
	domain := strings.TrimSpace(appDomain)
	if domain == "localhost" || strings.HasPrefix(domain, "localhost:") {
		out = append(out, "http://localhost:3000", "http://localhost:5173", "http://localhost:5342")
	} else {
		out = append(out, "https://"+domain, "https://app."+domain)
	}
	return dedupeStringSlice(out)
}

func dedupeStringSlice(items []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(items))
	for _, item := range items {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		if _, ok := seen[item]; ok {
			continue
		}
		seen[item] = struct{}{}
		out = append(out, item)
	}
	return out
}

func randomHex(numBytes int) (string, error) {
	buf := make([]byte, numBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}
