package cli

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"net"
	"net/url"
	"os"
	"strings"
)

func handleInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(os.Stdout)

	output := fs.String("output", ".env", "Output env file path")
	force := fs.Bool("force", false, "Overwrite output file if it exists")
	siteURL := fs.String("site-url", "https://api.example.com", "Public API URL")
	appDomain := fs.String("app-domain", "example.com", "Application base domain")
	databaseURL := fs.String("database-url", "", "PostgreSQL connection string")
	strictSecurity := fs.Bool("strict-security", false, "Enable strict startup security checks")
	debug := fs.Bool("debug", false, "Enable debug mode")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if strings.TrimSpace(*siteURL) == "" {
		return errors.New("site-url is required")
	}
	if strings.TrimSpace(*appDomain) == "" {
		return errors.New("app-domain is required")
	}
	if _, err := url.ParseRequestURI(*siteURL); err != nil {
		return fmt.Errorf("invalid --site-url: %w", err)
	}

	if _, err := os.Stat(*output); err == nil && !*force {
		return fmt.Errorf("file already exists: %s (use --force to overwrite)", *output)
	}

	jwtSecret, err := randomHex(64)
	if err != nil {
		return fmt.Errorf("generate JWT secret: %w", err)
	}
	dbPassword, err := randomHex(24)
	if err != nil {
		return fmt.Errorf("generate DB password: %w", err)
	}

	dbUser := "ozybase"
	dbName := "ozybase"
	dbSSLMode := "disable"
	resolvedDatabaseURL := strings.TrimSpace(*databaseURL)
	if resolvedDatabaseURL == "" {
		resolvedDatabaseURL = fmt.Sprintf("postgres://%s:%s@db:5432/%s?sslmode=%s", dbUser, dbPassword, dbName, dbSSLMode)
	} else {
		normalizedURL, normalizedSSLMode, err := normalizeDatabaseURL(resolvedDatabaseURL)
		if err != nil {
			return fmt.Errorf("invalid --database-url: %w", err)
		}
		resolvedDatabaseURL = normalizedURL
		dbSSLMode = normalizedSSLMode
	}

	allowedOrigins := deriveOrigins(*siteURL, *appDomain)
	envContent := renderEnv(initEnvData{
		SiteURL:         *siteURL,
		AppDomain:       *appDomain,
		AllowedOrigins:  strings.Join(allowedOrigins, ","),
		JWTSecret:       jwtSecret,
		DatabaseURL:     resolvedDatabaseURL,
		DBUser:          dbUser,
		DBPassword:      dbPassword,
		DBName:          dbName,
		DBSSLMode:       dbSSLMode,
		StrictSecurity:  *strictSecurity,
		Debug:           *debug,
		RateLimitRPS:    "20",
		RateLimitBurst:  "20",
		BodyLimit:       "10M",
		DefaultSMTPPort: "587",
	})

	if err := os.WriteFile(*output, []byte(envContent), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", *output, err)
	}

	fmt.Printf("env file created: %s\n", *output)
	fmt.Println("next: review domains/database settings if needed, then run: ozybase")
	return nil
}

type initEnvData struct {
	SiteURL         string
	AppDomain       string
	AllowedOrigins  string
	JWTSecret       string
	DatabaseURL     string
	DBUser          string
	DBPassword      string
	DBName          string
	DBSSLMode       string
	StrictSecurity  bool
	Debug           bool
	RateLimitRPS    string
	RateLimitBurst  string
	BodyLimit       string
	DefaultSMTPPort string
}

func renderEnv(data initEnvData) string {
	return fmt.Sprintf(`# Generated by: ozybase init
PORT="8090"
SITE_URL="%s"
APP_DOMAIN="%s"
ALLOWED_ORIGINS="%s"

JWT_SECRET="%s"
OZY_STRICT_SECURITY="%t"
DEBUG="%t"

DB_USER="%s"
DB_PASSWORD="%s"
DB_NAME="%s"
DB_SSLMODE="%s"
DATABASE_URL="%s"
RATE_LIMIT_RPS="%s"
RATE_LIMIT_BURST="%s"
BODY_LIMIT="%s"

SMTP_HOST=""
SMTP_PORT="%s"
SMTP_USER=""
SMTP_PASSWORD=""
SMTP_FROM="noreply@%s"
`, data.SiteURL, data.AppDomain, data.AllowedOrigins, data.JWTSecret, data.StrictSecurity, data.Debug, data.DBUser, data.DBPassword, data.DBName, data.DBSSLMode, data.DatabaseURL, data.RateLimitRPS, data.RateLimitBurst, data.BodyLimit, data.DefaultSMTPPort, data.AppDomain)
}

func deriveOrigins(siteURL, appDomain string) []string {
	out := []string{strings.TrimRight(siteURL, "/")}
	domain := strings.TrimSpace(appDomain)
	if domain == "localhost" || strings.HasPrefix(domain, "localhost:") {
		out = append(out, "http://localhost:3000", "http://localhost:5173", "http://localhost:5342")
	} else {
		out = append(out, "https://"+domain, "https://app."+domain)
	}
	return dedupeStringSlice(out)
}

func dedupeStringSlice(items []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(items))
	for _, item := range items {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		if _, ok := seen[item]; ok {
			continue
		}
		seen[item] = struct{}{}
		out = append(out, item)
	}
	return out
}

func randomHex(numBytes int) (string, error) {
	buf := make([]byte, numBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func normalizeDatabaseURL(raw string) (string, string, error) {
	parsed, err := url.Parse(raw)
	if err != nil {
		return "", "", err
	}
	if parsed.Scheme == "" || parsed.Host == "" {
		return "", "", errors.New("database URL must include scheme and host")
	}

	host := strings.ToLower(strings.TrimSpace(parsed.Hostname()))
	defaultSSLMode := "require"
	if isLocalDatabaseHost(host) {
		defaultSSLMode = "disable"
	}

	q := parsed.Query()
	sslmode := strings.ToLower(strings.TrimSpace(q.Get("sslmode")))
	if sslmode == "" {
		sslmode = defaultSSLMode
		q.Set("sslmode", sslmode)
		parsed.RawQuery = q.Encode()
	}

	// Force safer default for external hosts if insecure mode is used.
	if !isLocalDatabaseHost(host) && (sslmode == "disable" || sslmode == "allow" || sslmode == "prefer") {
		sslmode = "require"
		q.Set("sslmode", sslmode)
		parsed.RawQuery = q.Encode()
	}

	return parsed.String(), sslmode, nil
}

func isLocalDatabaseHost(host string) bool {
	if host == "localhost" || host == "db" {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}
