package typegen

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/Xangel0s/OzyBase/internal/data"
)

type Generator struct {
	db *data.DB
}

func NewGenerator(db *data.DB) *Generator {
	return &Generator{db: db}
}

type TableMetadata struct {
	Name   string
	Fields []data.FieldSchema
}

func (g *Generator) Generate(outputPath string) (err error) {
	ctx := context.Background()
	rows, err := g.db.Pool.Query(ctx, "SELECT name, schema_def FROM _v_collections ORDER BY name ASC")
	if err != nil {
		return fmt.Errorf("failed to query collections: %w", err)
	}
	defer rows.Close()

	var tables []TableMetadata
	for rows.Next() {
		var name string
		var schemaJSON []byte
		if err := rows.Scan(&name, &schemaJSON); err != nil {
			return err
		}

		var fields []data.FieldSchema
		if err := json.Unmarshal(schemaJSON, &fields); err != nil {
			return err
		}

		tables = append(tables, TableMetadata{
			Name:   name,
			Fields: fields,
		})
	}

	f, err := os.Create(filepath.Clean(outputPath))
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil && err == nil {
			err = fmt.Errorf("failed to close generated type file: %w", closeErr)
		}
	}()

	tmpl, err := template.New("ts").Funcs(template.FuncMap{
		"MapType": mapType,
	}).Parse(tsTemplate)
	if err != nil {
		return err
	}

	if err = tmpl.Execute(f, map[string]any{
		"Tables": tables,
	}); err != nil {
		return fmt.Errorf("failed to render generated types: %w", err)
	}
	return nil
}

func mapType(field data.FieldSchema) string {
	switch strings.ToLower(field.Type) {
	case "text", "uuid", "datetime":
		return "string"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	case "json":
		return "Json"
	default:
		return "any"
	}
}

const tsTemplate = `/**
 * AUTO-GENERATED BY OzyBase - DO NOT EDIT MANUALLY
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      {{- range .Tables}}
      {{.Name}}: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          {{- range .Fields}}
          {{.Name}}: {{MapType .}}{{if not .Required}} | null{{end}}
          {{- end}}
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          {{- range .Fields}}
          {{.Name}}{{if not .Required}}?{{end}}: {{MapType .}}{{if not .Required}} | null{{end}}
          {{- end}}
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          {{- range .Fields}}
          {{.Name}}?: {{MapType .}}{{if not .Required}} | null{{end}}
          {{- end}}
        }
      }
      {{- end}}
    }
  }
}
`
